-- ============================================
-- UrbanCart Retail Shop Analytics
-- SQL Queries Q1 to Q25 | PostgreSQL
-- Database: PostgreSQL (pgAdmin 4)
-- Tables: FactOrders, FactOrderItems,
--         DimCustomers, DimProducts, FactPayment
-- Author Name:Sajib Chowdhury
-- Role:Data Enthusiast
-- ============================================

-- -----------------------------------------------
-- Q1. How many total orders has UrbanCart received so far?
-- -----------------------------------------------
SELECT COUNT(DISTINCT order_id) AS "Total Orders"
FROM public."FactOrderItems";
-- Result: 1,200 total orders [cite: 3-8]

-- -----------------------------------------------
-- Q2. Which cities generate the highest number of orders & revenue?
-- -----------------------------------------------
SELECT c.city AS "City", COUNT(o.order_id) AS "Total Orders", SUM(p.quantity * q.unit_price) AS "Total Revenue"
FROM public."FactOrders" o
JOIN public."DimCustomers" c ON o.customer_id = c.customer_id
JOIN public."FactOrderItems" p ON o.order_id = p.order_id
JOIN public."DimProducts" q ON p.product_id = q.product_id
GROUP BY 1
ORDER BY 2 DESC;
-- Result: Barishal leads [cite: 9-23]

-- -----------------------------------------------
-- Q3. What percent of total customers uses Gmail?
-- -----------------------------------------------
SELECT COUNT(CASE WHEN email ILIKE '%@gmail%' THEN 1 END) * 100 / COUNT(customer_id) AS "Gmail Users (%)"
FROM public."DimCustomers";
-- Result: 70% [cite: 24-31]

-- -----------------------------------------------
-- Q4. What is the monthly trend of total orders over time?
-- -----------------------------------------------
SELECT TO_CHAR(order_date::DATE, 'Month YYYY') AS "Month", COUNT(order_id) AS "Total Orders"
FROM public."FactOrders"
GROUP BY 1
ORDER BY 1 DESC;
-- Result: Oct 2025 peaked at 413 orders [cite: 32-42]

-- -----------------------------------------------
-- Q5. What is the order completion rate across all orders?
-- -----------------------------------------------
SELECT ROUND((COUNT(CASE WHEN status ILIKE 'Completed' THEN 1 END) * 100.0 / COUNT(DISTINCT order_id)), 2) AS "Completion Rate(%)"
FROM public."FactOrders";
-- Result: 59.4% [cite: 43-49]

-- -----------------------------------------------
-- Q6. What is the total revenue generated by UrbanCart?
-- -----------------------------------------------
SELECT SUM(o.quantity * c.unit_price) AS "Total Revenue (BDT)"
FROM public."FactOrderItems" o
JOIN public."DimProducts" c ON o.product_id = c.product_id;
-- Result: BDT 22,45,122 [cite: 50-56]

-- -----------------------------------------------
-- Q7. Which product categories contribute the most to total revenue?
-- -----------------------------------------------
SELECT c.category AS "Product Category", SUM(o.quantity * c.unit_price) AS "Total Revenue"
FROM public."FactOrderItems" o
JOIN public."DimProducts" c ON o.product_id = c.product_id
GROUP BY 1
ORDER BY 2 DESC;
-- Result: Fashion leads [cite: 57-67]

-- -----------------------------------------------
-- Q8. Which individual products generate the highest revenue?
-- -----------------------------------------------
SELECT c.product_name AS "Product Name", SUM(o.quantity * c.unit_price) AS "Total Revenue"
FROM public."FactOrderItems" o
JOIN public."DimProducts" c ON o.product_id = c.product_id
GROUP BY 1
ORDER BY 2 DESC;
-- Result: Power Bank 10000mAh tops [cite: 68-79]

-- -----------------------------------------------
-- Q9. What is the Average Order Value (AOV) and Average Basket Size?
-- -----------------------------------------------
-- Average Order Value
SELECT ROUND(SUM(o.quantity * c.unit_price) / COUNT(DISTINCT order_id), 2) AS "AOV"
FROM public."FactOrderItems" o
JOIN public."DimProducts" c ON o.product_id = c.product_id;

-- Average Basket Size
SELECT ROUND(SUM(quantity) / COUNT(DISTINCT order_id), 2) AS "Average Basket Size"
FROM public."FactOrderItems";
-- Result: AOV = BDT 1,870.94 | Average Basket Size = 9.96 items [cite: 80-93]

-- -----------------------------------------------
-- Q10. Which products are at risk of stock-out?
-- -----------------------------------------------
SELECT product_name AS "Product", category AS "Product Category", stock AS "Stock",
CASE
    WHEN stock <= 100 THEN 'Critical'
    WHEN stock <= 200 THEN 'Low'
    WHEN stock <= 500 THEN 'Medium'
    ELSE 'Healthy'
END AS "Status"
FROM public."DimProducts"
ORDER BY 3 ASC;
-- Result: Power Bank 10000mAh is Critical [cite: 94-111]

-- -----------------------------------------------
-- Q11. Which customers contribute the highest total revenue?
-- -----------------------------------------------
SELECT q.customer_id AS "Customer ID", r.full_name AS "Name", SUM(o.quantity * c.unit_price) AS "Total Revenue"
FROM public."FactOrderItems" o
JOIN public."DimProducts" c ON o.product_id = c.product_id
JOIN public."FactOrders" q ON o.order_id = q.order_id
JOIN public."DimCustomers" r ON q.customer_id = r.customer_id
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 10;
-- Result: Raisa (ID 70) [cite: 112-127]

-- -----------------------------------------------
-- Q12. Cancellation rate by city and customer.
-- -----------------------------------------------
-- City
SELECT o.city AS "City", COUNT(c.order_id) AS "Total Orders", COUNT(CASE WHEN c.status ILIKE '%cancelled%' THEN 1 END) AS "Cancelled Orders",
ROUND(COUNT(CASE WHEN c.status ILIKE '%cancelled%' THEN 1 END) * 100.0 / COUNT(c.order_id), 2) AS "Cancellation Rate (%)"
FROM public."FactOrders" c
JOIN public."DimCustomers" o ON c.customer_id = o.customer_id
GROUP BY o.city
ORDER BY "Cancellation Rate (%)" DESC;

-- Customer
SELECT o.full_name AS "Customer Name", COUNT(c.order_id) AS "Total Orders", COUNT(CASE WHEN c.status ILIKE '%cancelled%' THEN 1 END) AS "Cancelled Orders",
ROUND(COUNT(CASE WHEN c.status ILIKE '%cancelled%' THEN 1 END) * 100.0 / COUNT(c.order_id), 2) AS "Cancellation Rate (%)"
FROM public."FactOrders" c
JOIN public."DimCustomers" o ON c.customer_id = o.customer_id
GROUP BY o.full_name
ORDER BY "Cancellation Rate (%)" DESC;
-- Result: Gazipur (27%) | Tanvir (50%) [cite: 128-159]

-- -----------------------------------------------
-- Q13. Gender purchasing patterns by category.
-- -----------------------------------------------
SELECT c."Gender", COUNT(DISTINCT o.order_id) AS "Total Orders", SUM(p.unit_price * oi.quantity) AS "Total Revenue (BDT)",
ROUND(AVG(p.unit_price * oi.quantity), 2) AS "Avg Order Value", COUNT(CASE WHEN o.status ILIKE '%cancelled%' THEN 1 END) AS "Cancelled Orders",
ROUND(COUNT(CASE WHEN o.status ILIKE '%cancelled%' THEN 1 END) * 100.0 / COUNT(o.order_id), 2) AS "Cancel Rate (%)"
FROM public."FactOrders" o
JOIN public."DimCustomers" c ON o.customer_id = c.customer_id
JOIN public."FactOrderItems" oi ON o.order_id = oi.order_id
JOIN public."DimProducts" p ON oi.product_id = p.product_id
GROUP BY 1;
-- Result: Male 686 orders, Female 514 [cite: 160-178]

-- -----------------------------------------------
-- Q14. Purchasing behavior over time since account creation.
-- -----------------------------------------------
SELECT dc.customer_id AS "Customer ID", dc.full_name AS "Customer Name",
CASE
    WHEN (TO_DATE(fo.order_date, 'MM/DD/YYYY') - TO_DATE(dc.created_at, 'MM/DD/YYYY')) <= 30 THEN '0-30 days'
    WHEN (TO_DATE(fo.order_date, 'MM/DD/YYYY') - TO_DATE(dc.created_at, 'MM/DD/YYYY')) <= 60 THEN '31-60 days'
    ELSE '60+ days'
END AS "Period",
COUNT(DISTINCT fo.order_id) AS "Total Orders", SUM(foi.quantity) AS "Total Items"
FROM public."FactOrders" fo
JOIN public."DimCustomers" dc ON fo.customer_id = dc.customer_id
JOIN public."FactOrderItems" foi ON fo.order_id = foi.order_id
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;
-- Result: Varied across periods [cite: 179-203]

-- -----------------------------------------------
-- Q15. Customers who ordered in October but not December.
-- -----------------------------------------------
SELECT DISTINCT c.customer_id AS "Customer ID", c.full_name AS "Customer Name", c.city AS "Customer City"
FROM public."DimCustomers" c
WHERE c.customer_id IN (SELECT customer_id FROM public."FactOrders" WHERE EXTRACT(MONTH FROM TO_DATE(order_date, 'MM/DD/YYYY')) = 10)
AND c.customer_id NOT IN (SELECT customer_id FROM public."FactOrders" WHERE EXTRACT(MONTH FROM TO_DATE(order_date, 'MM/DD/YYYY')) = 12);
-- Result: 17 customers [cite: 204-218]

-- -----------------------------------------------
-- Q16. Customers who ordered in both October & December.
-- -----------------------------------------------
SELECT DISTINCT c.customer_id AS "Customer ID", c.full_name AS "Customer Name", c.city AS "Customer City"
FROM public."DimCustomers" c
WHERE c.customer_id IN (SELECT customer_id FROM public."FactOrders" WHERE EXTRACT(MONTH FROM TO_DATE(order_date, 'MM/DD/YYYY')) = 10)
AND c.customer_id IN (SELECT customer_id FROM public."FactOrders" WHERE EXTRACT(MONTH FROM TO_DATE(order_date, 'MM/DD/YYYY')) = 12);
-- Result: 81 customers [cite: 219-233]

-- -----------------------------------------------
-- Q17. Most frequently used payment methods.
-- -----------------------------------------------
SELECT method AS "Payment Method", COUNT(DISTINCT order_id) AS "Total Orders"
FROM public."FactPayment"
GROUP BY 1
ORDER BY 2 DESC;
-- Result: COD 488 [cite: 234-243]

-- -----------------------------------------------
-- Q18. Relationship between payment method and order status.
-- -----------------------------------------------
SELECT o.method AS "Payment Method", c.status AS "Order Status", COUNT(DISTINCT o.order_id) AS "Total Orders"
FROM public."FactPayment" o
JOIN public."FactOrders" c ON o.order_id = c.order_id
GROUP BY 1, 2
ORDER BY 1, 3 DESC;
-- Result: COD completions 300 [cite: 244-257]

-- -----------------------------------------------
-- Q19. City preferences for payment methods.
-- -----------------------------------------------
SELECT p.city AS "City", o.method AS "Payment Method", COUNT(DISTINCT o.payment_id) AS "Transaction Count",
ROUND(COUNT(DISTINCT o.payment_id) * 100.0 / SUM(COUNT(DISTINCT o.payment_id)) OVER (PARTITION BY p.city), 2) AS "City Share (%)"
FROM public."FactPayment" o
JOIN public."FactOrders" c ON o.order_id = c.order_id
JOIN public."DimCustomers" p ON c.customer_id = p.customer_id
GROUP BY 1, 2
ORDER BY 1, 3 DESC;
-- Result: COD preferred all cities [cite: 258-277]

-- -----------------------------------------------
-- Q20. Higher-value orders associated with payment methods.
-- -----------------------------------------------
SELECT o.method AS "Payment Method", SUM(p.quantity * q.unit_price) AS "Total Revenue"
FROM public."FactPayment" o
JOIN public."FactOrderItems" p ON o.order_id = p.order_id
JOIN public."DimProducts" q ON p.product_id = q.product_id
GROUP BY 1
ORDER BY 2 DESC;
-- Result: COD = BDT 898,761 [cite: 278-289]

-- -----------------------------------------------
-- Q21. Average number of items per order by payment method.
-- -----------------------------------------------
SELECT c.method AS "Method", ROUND(AVG(o.quantity), 2) AS "Average Number of Items"
FROM public."FactOrderItems" o
JOIN public."FactPayment" c ON o.order_id = c.order_id
GROUP BY 1
ORDER BY 2 DESC;
-- Result: Debit Card 2.63 [cite: 290-301]

-- -----------------------------------------------
-- Q22. Difference between category average price and product price.
-- -----------------------------------------------
SELECT product_name AS "Product Name", category AS "Product Category", unit_price AS "Unit Price",
ROUND(AVG(unit_price) OVER (PARTITION BY category), 2) AS "Category Avg Price",
unit_price - ROUND(AVG(unit_price) OVER (PARTITION BY category), 2) AS "Difference"
FROM public."DimProducts"
ORDER BY 5 ASC;
-- Result: Earphones highest negative diff [cite: 302-317]

-- -----------------------------------------------
-- Q23. Products most frequently purchased together.
-- -----------------------------------------------
SELECT f1.product_id AS "Product 1", f2.product_id AS "Product 2", COUNT(*) AS "Pair Count"
FROM public."FactOrderItems" f1
JOIN public."FactOrderItems" f2 ON f1.order_id = f2.order_id AND f1.product_id < f2.product_id
GROUP BY 1, 2
ORDER BY 3 DESC;
-- Result: Prod 24 & 30 most paired [cite: 318-331]

-- -----------------------------------------------
-- Q24. Product pairs generating highest total revenue.
-- -----------------------------------------------
SELECT f1.product_id AS "Product 1", f2.product_id AS "Product 2",
SUM((p1.quantity * p1.unit_price) + (p2.quantity * p2.unit_price)) AS "Total Revenue"
FROM public."FactOrderItems" f1
JOIN public."FactOrderItems" f2 ON f1.order_id = f2.order_id AND f1.product_id < f2.product_id
JOIN public."DimProducts" p1 ON f1.product_id = p1.product_id
JOIN public."DimProducts" p2 ON f2.product_id = p2.product_id
GROUP BY 1, 2
ORDER BY 3 DESC;
-- Result: Prod 9 & 40 highest [cite: 332-348]

-- -----------------------------------------------
-- Q25. Daily report: Date, Total Orders, Items, Completed, Cancelled, Revenue.
-- -----------------------------------------------
SELECT TO_DATE(o.order_date, 'MM/DD/YYYY') AS "Order Date",
COUNT(DISTINCT o.order_id) AS "Total Orders",
SUM(c.quantity) AS "Total Items",
COUNT(DISTINCT CASE WHEN o.status = 'Completed' THEN o.order_id END) AS "Completed Orders",
COUNT(DISTINCT CASE WHEN o.status = 'Cancelled' THEN o.order_id END) AS "Cancelled Orders",
COUNT(DISTINCT CASE WHEN o.status = 'Pending' THEN o.order_id END) AS "Pending Orders",
SUM(c.quantity * q.unit_price) AS "Total Revenue"
FROM public."FactOrders" o
JOIN public."FactOrderItems" c ON o.order_id = c.order_id
JOIN public."DimProducts" q ON c.product_id = q.product_id
GROUP BY 1
ORDER BY 1;
-- Result: Daily breakdown [cite: 349-353]